### ISSUE TITLE
Styles not working on my iPad HA App with HA 2024.8

### ISSUE THREAD

**Issue by bdormael** [Nerwyn/service-call-tile-feature#45]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
4.0.7 with HA 2024.8 & iOS 18 beta 5
**Last working release (if known):**
4.0.7 with HA 2024.7 & iOS 18 beta 5
**Browser and Operating System:**
iOS 18 beta 8 & HA 2024.8

**Description of problem:**
Weird issue : with the HA App on my iPad the Styles are not applied (fonts, colours, etc.)
With Safari on that same iPad it is working fine.

I cleared the cache from the HA App already, even uninstalled and reinstalled.

Other cards where I can use card_mod are still working fine

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: cover.gordijnen_living
        options:
          - icon: mdi:arrow-expand-horizontal
            option: open
            label: |
              {% if is_state("sensor.gordijnen_living_status", "Open") %}
                geopend
              {% else %}
                openen
              {% endif %}
            tap_action:
              service: cover.open_cover
              action: call-service
              target:
                entity_id: cover.gordijnen_living
            type: button
            styles: |-
              :host {
                --color: {% if is_state("cover.gordijnen_living", "opening")%}
                orange
              {% elif is_state("cover.gordijnen_living", "closing")%}  
                orange
              {% else %}
                var(--green-color)
              {% endif %}
              ;
                --opacity: {% if is_state("sensor.gordijnen_living_status", "Open") %}
                0.4
              {% else %}
                0
              {% endif %}
              ;
                height: 50px;
              }
              .label {
                font-weight: normal;
              }
            entity_id: cover.gordijnen_living
          - icon: mdi:arrow-collapse-horizontal
            option: close
            label: |
              {% if is_state("sensor.gordijnen_living_status", "Gesloten") %}
                gesloten
              {% else %}
                sluiten
              {% endif %}
            tap_action:
              service: cover.close_cover
              action: call-service
              target:
                entity_id: cover.gordijnen_living
            type: button
            styles: |-
              :host {
                --color: {% if is_state("cover.gordijnen_living", "opening")%}
                orange
              {% elif is_state("cover.gordijnen_living", "closing")%}  
                orange
              {% else %}
                var(--red-color)
              {% endif %}
              ;
                --opacity: {% if is_state("sensor.gordijnen_living_status", "Gesloten") %}
                0.4
              {% else %}
                0
              {% endif %}
              ;
                height: 50px;
              }
              .label {
                font-weight: normal;
              }
            entity_id: cover.gordijnen_living
        styles: |-
          :host {
            --hover-opacity: 0.2;
            height: 50px;
          }
type: tile
name: Gordijnen
entity: cover.gordijnen_living
icon: mdi:curtains
tap_action:
  action: none
icon_tap_action:
  action: none
layout_options:
  grid_columns: 4
  grid_rows: 2
card_mod:
  style:
    ha-tile-info$: |
      .secondary {
        visibility: hidden;
      }
      .secondary:before {
        visibility: visible;
        {% if is_state("cover.gordijnen_living", "opening")%}
          content: "aan het openen..."
        {% elif is_state("cover.gordijnen_living", "closing")%}  
          content: "aan het sluiten..."
        {% else %}
          {% from 'easy_time.jinja' import easy_relative_time %}
          content: "{{ states('sensor.gordijnen_living_status') }}"
        {% endif %}
      }
    .: |
      ha-card {
          {% if is_state('sensor.gordijnen_living_status','Gesloten') and (is_state("cover.gordijnen_living", "open") or is_state("cover.gordijnen_living", "closed"))%}
                --tile-color: red !important; 
          {% elif is_state('sensor.gordijnen_living_status','Open') and (is_state("cover.gordijnen_living", "open") or is_state("cover.gordijnen_living", "closed"))%} 
                --tile-color: green !important;
          {% else %}
                --tile-color: orange !important;
          {% endif %}
          
            }
```

**Additional information:**

**Comment by Nerwyn** [comment]
[The only difference between 4.0.7 and 4.0.8 is that the configuration UI was updated to use a newer tabs element](https://github.com/Nerwyn/service-call-tile-feature/compare/4.0.7...4.0.8). Do styles work again if you downgrade to 4.0.7? I just checked on an old iPhone SE and the styles are working fine in app.

**Comment by bdormael** [comment]
Hi, I’ve had 4.0.7, I know upgraded to 4.0.8 and it’s the same issue I’m afraid, really weird.
On my iPhone it is also working fine, just not on my iPad.

As a test I did a restore to Home assistant 2024.7 (from Tuesday with your app version 4.0.7 and then it works fine again.
So it looks like it has something to do with the new HA 2024.8 ?

**Comment by Nerwyn** [comment]
Can you take before and after screenshots? Are all the styles not applying or just some?

**Comment by bdormael** [comment]
non working version:
![IMG_3729](https://github.com/user-attachments/assets/1b4f5e07-3223-4123-a1c2-52ebc3898560)
working version:
![IMG_1642](https://github.com/user-attachments/assets/34a968f5-6d9f-4dda-ab2f-29bd5c033a67)

none of the styling is working (color, height, opacity) in the first screenshot (with 4.0.8 and HA 2024.8)

I also have custom:paper-buttons-row and there styling works perfect.

**Comment by Nerwyn** [comment]
Most of the styles seem to be applying fine, but selector hover styles aren't working for me on iPhone or Android.

**Comment by Nerwyn** [comment]
The 4.0.9 alpha should fix the selector option active styles on mobile, but I'm not sure about the rest of your issues as your provided config is working for me. Do you have screenshots of what your tile cover card looks like before and after, or the config of the tile card you provided screenshots for?

**Comment by bdormael** [comment]
Hi,
Indeed, 4.0.9 doesn't solve my issue. It's the same screenshot as a couple of posts above (where nothing is greyed out.

Here the YAML for that card:
`
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: alarm_control_panel.alarmo
        value_attribute: arm_mode
        options:
          - icon: mdi:lock
            option: armed_away
            label: afwezig
            tap_action:
              action: perform-action
              target:
                entity_id: alarm_control_panel.alarmo
              perform_action: alarm_control_panel.alarm_arm_away
            type: button
            styles: |-
              :host {
                --color: var(--red-color);
                --opacity: {% if is_state_attr("alarm_control_panel.alarmo", "arm_mode", "armed_away") %}
                0.7
              {% else %}
                0
              {% endif %}
              ;
                --icon-color: initial;
                --label-color: initial;
                height: 50px;
              }
              .label {
                font-weight: normal;
              }
            entity_id: alarm_control_panel.alarmo
          - icon: mdi:moon-waning-crescent
            option: armed_night
            label: nacht
            tap_action:
              action: perform-action
              target:
                entity_id: alarm_control_panel.alarmo
              perform_action: alarm_control_panel.alarm_arm_night
            type: button
            styles: |-
              :host {
                --color: var(--orange-color);
                --opacity: {% if is_state_attr("alarm_control_panel.alarmo", "arm_mode", "armed_night") %}
                0.7
              {% else %}
                0
              {% endif %}
              ;
                --icon-color: initial;
                --label-color: initial;
                height: 50px;
              }
              .label {
                font-weight: normal;
              }
            entity_id: alarm_control_panel.alarmo
          - icon: mdi:power
            option: disarmed
            label: uit
            tap_action:
              action: perform-action
              target:
                entity_id: alarm_control_panel.alarmo
              perform_action: alarm_control_panel.alarm_disarm
            type: button
            styles: |-
              :host {
                --color: var(--grey-color);
                --opacity: 
                    {% if is_state("alarm_control_panel.alarmo", "disarmed") %}
                     0.7
                    {% else %}
                    0
                    {% endif %}
                    ;
                --icon-color: initial;
                --label-color: initial;
                height: 50px;
                }
                .label {
                  font-weight: normal;
                }
            entity_id: alarm_control_panel.alarmo
        styles: |-
          :host {
            --hover-opacity: 0.2;
            height: 50px;
          }
type: tile
entity: alarm_control_panel.alarmo
vertical: false
show_entity_picture: false
tap_action:
  action: none
icon_tap_action:
  action: none
state_content:
  - state
  - last-changed
name: Alarm
layout_options:
  grid_columns: 4
  grid_rows: 2
card_mod:
  style: |
    ha-card { 
          --state-alarm_control_panel-armed_away-color: rgb(218, 0, 0);
          --state-alarm_control_panel-armed_night-color: orange;
          --state-alarm_control_panel-arming-color: orange;
          --state-alarm_control_panel-disarming-color: orange;
          --state-alarm_control_panel-pending-color: orange;
          --state-alarm_control_panel-triggered-color: rgb(218, 0, 0);
          --state-alarm_control_panel-disarmed-color: grey;
             }
`

**Comment by Nerwyn** [comment]
That config is working for me on an old iPhone and other devices. I think this is a really persistent caching issue. Have you tried clearing cache and restarting the device? Safari and Home Assistant should be using the same webview and have the same behavior. If it's working on one app but not another then it points to an app cache issue. Other than that I'm stumped.

**Comment by bdormael** [comment]
Hi, deleted cache already multiple times and restarted multiple times, same issue.
Oh well, maybe I need to wait for a new update of my iPad, in the meantime I’ll use paper-buttons-row to mimic your plugin.

Thx anyway for your support.

**Comment by bdormael** [comment]
UPDATE: since Core 204.8.3 and OS 13.1 the issues has been solved.
